import {
  Box,
  Container,
  Stack,
  useTheme,
  Typography,
  ThemeProvider,
  Grid,
} from "@mui/material";
import BannerImage from "@/public/images/home_banner_4.webp";
import { muiTheme } from "@/reusables/theme";
import Head from "next/head";
import { NavItem } from "./NavItem";
import { v4 as uuid } from "uuid";
import { navItems } from "../config/navItems";

export function AppHome() {
  const theme = useTheme();
  return (
    <ThemeProvider theme={muiTheme}>
      <Head>
        <title>App Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            width: "100%",
            height: "100vh",
            backgroundImage: `url(${BannerImage.src})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <Stack
            direction={"row"}
            alignItems={"center"}
            width={"100%"}
            height="100%"
          >
            <Container maxWidth="md">
              <Stack
                direction={"column"}
                alignItems={"center"}
                width={"100%"}
                minHeight={"450px"}
                boxShadow={theme.shadows[19]}
                sx={{
                  backdropFilter: "blur(8px)",
                  backgroundColor: "rgba(41, 78, 87, 0.5)",
                  borderRadius: "24px",
                  border: "1px solid rgb(76, 119, 127, 0.9)",
                  padding: "40px",
                  textAlign: "center",
                }}
              >
                <Box maxWidth={"70%"}>
                  <Typography
                    color={theme.palette.common.white}
                    variant="h3"
                    fontWeight={"800"}
                  >
                    Hi, There
                  </Typography>
                  <Typography
                    variant="body1"
                    fontSize={"20px"}
                    lineHeight={"1.2"}
                    color={theme.palette.common.white}
                  >
                    Programs must be written for people to read, and only
                    incidentally for machines to execute.
                  </Typography>
                </Box>

                <Box mt={"32px"}>
                  <Grid container spacing={2}>
                    {navItems.map((itm) => (
                      <Grid item key={uuid()}>
                        <NavItem
                          name={itm.name}
                          icon={itm.icon}
                          iconColor={itm.iconColor}
                          url={itm.url}
                          onClick={(url) => {
                            // go to url via router
                          }}
                        />
                      </Grid>
                    ))}
                  </Grid>
                </Box>
              </Stack>
            </Container>
          </Stack>
        </Box>
      </main>
    </ThemeProvider>
  );
}
